# Generated by Django 4.2.11 on 2024-05-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("IN", "Information"),
                            ("IM", "Important"),
                            ("WA", "Warning"),
                            ("CR", "Critical"),
                        ],
                        default="IN",
                        max_length=2,
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                ("content", models.TextField()),
                ("notified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Announcement",
                "verbose_name_plural": "Announcements",
                "ordering": ["-id"],
            },
        ),
    ]
