# Generated by Django 4.2.11 on 2024-08-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announcement", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="send_mail",
            field=models.BooleanField(default=False),
        ),
    ]
