# Generated by Django 4.2.11 on 2024-05-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escavador", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processofonteescavador",
            name="data_ultima_movimentacao",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
