# Generated by Django 4.2.11 on 2024-05-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escavador", "0002_alter_processofonteescavador_data_ultima_movimentacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processofonteescavador",
            name="status_predito",
            field=models.CharField(
                blank=True,
                choices=[("A", "Ativo"), ("I", "Inativo")],
                default=None,
                max_length=1,
                null=True,
            ),
        ),
    ]
