# Generated by Django 4.2.11 on 2024-05-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escavador", "0003_alter_processofonteescavador_status_predito"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processofonteescavador",
            name="fisico",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="processofonteescavador",
            name="url",
            field=models.CharField(
                blank=True, default=None, max_length=1024, null=True
            ),
        ),
    ]
