# Generated by Django 4.2.11 on 2024-05-24 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("escavador", "0004_alter_processofonteescavador_fisico_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="envolvidoescavador",
            name="processo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="envolvidos_processo",
                to="escavador.processoescavador",
            ),
        ),
    ]
