# Generated by Django 4.2.11 on 2024-07-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escavador", "0006_alter_processofonteescavador_id_escavador"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movimentacaoescavador",
            name="fonte",
        ),
        migrations.AddField(
            model_name="movimentacaoescavador",
            name="fonte_caderno",
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="movimentacaoescavador",
            name="fonte_grau",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="movimentacaoescavador",
            name="fonte_grau_formatado",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="movimentacaoescavador",
            name="fonte_id",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="movimentacaoescavador",
            name="fonte_nome",
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="movimentacaoescavador",
            name="fonte_sigla",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="movimentacaoescavador",
            name="fonte_tipo",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name="MovimentacaoFonteEscavador",
        ),
    ]
