# Generated by Django 4.2.15 on 2024-09-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escavador", "0008_alter_processofonteescavador_processo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimentacaoescavador",
            name="id_escavador",
            field=models.PositiveBigIntegerField(),
        ),
    ]
