# Generated by Django 4.2.11 on 2024-05-11 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lawsuit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cnj_number", models.CharField(max_length=50, unique=True)),
                ("automatic_update", models.BooleanField(default=False)),
                (
                    "update_interval",
                    models.CharField(
                        choices=[
                            ("NA", "N/A"),
                            ("DA", "Daily"),
                            ("AL", "Alternate Days"),
                            ("WE", "Weekly"),
                            ("MO", "Monthly"),
                        ],
                        default="NA",
                        max_length=2,
                    ),
                ),
                ("last_check", models.DateTimeField(blank=True, null=True)),
                ("observation", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lawsuit",
                "verbose_name_plural": "Lawsuits",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="LawsuitComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lawsuit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lawsuit.lawsuit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lawsuit Comment",
                "verbose_name_plural": "Lawsuit Comments",
                "ordering": ["-id"],
            },
        ),
    ]
