# Generated by Django 4.2.15 on 2024-09-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lawsuit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lawsuit",
            name="monitoring_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
