# Generated by Django 4.2.11 on 2024-05-14 00:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-id"],
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
        migrations.AlterModelOptions(
            name="notificationhistory",
            options={
                "ordering": ["-id"],
                "verbose_name": "Notification History",
                "verbose_name_plural": "Notification Histories",
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "ordering": ["-id"],
                "verbose_name": "Recipient",
                "verbose_name_plural": "Recipients",
            },
        ),
    ]
